export const metricSections = [
  { id: 'metrics', title: '2.1 Metrics' },
  { id: 'open-sets', title: '2.2 Open subsets of metric spaces' },
  { id: 'topology', title: '2.3 Topological spaces & continuity' },
  { id: 'metric-topology', title: '2.4 Metric topologies' },
  { id: 'connectedness', title: '2.5 Connectedness' },
  { id: 'compactness', title: '2.6 Compactness' },
  { id: 'sequences', title: '2.7 Sequences in metric spaces' },
  { id: 'cauchy', title: '2.8 Cauchy sequences' },
  { id: 'completions', title: '2.9 Completions' },
];

export const prerequisites = [
  'Set notation and functions',
  'Equivalence relations',
  'Sequences and limits in ℝ',
  'Countability and cardinality',
  'Basic real analysis (ε–δ arguments)',
];

const resultCards = [
  { section: 'open-sets', title: 'Proposition 2.9 — Arbitrary unions of opens', statement: 'In a metric space, the union of an arbitrary collection of open sets is open.', proof: 'Take u in the union. Choose one member Uᵢ containing u. Since Uᵢ is open, some ball Bᵣ(u) lies in Uᵢ, hence in the union.' },
  { section: 'open-sets', title: 'Proposition 2.10 — Finite intersections of opens', statement: 'In a metric space, the intersection of finitely many open sets is open.', proof: 'For u in ⋂ᵢ₌₁ⁿ Uᵢ, choose Bᵣᵢ(u) ⊆ Uᵢ. Put r = min{r₁,…,rₙ}; then Bᵣ(u) lies in every Uᵢ.' },
  { section: 'topology', title: 'Proposition 2.15 — Comparing topologies', statement: 'For topologies T₁,T₂ on X: T₂ ⊆ T₁ iff every T₂-neighbourhood contains a T₁-neighbourhood, iff id:(X,T₁)→(X,T₂) is continuous.', proof: 'Not provided in the notes (Exercise 1.19).' },
  { section: 'topology', title: 'Proposition 2.18 — Product projections', statement: 'The projections from X₁×X₂ are continuous. The product topology is the coarsest topology making both projections continuous.', proof: 'Projection preimages are open rectangles. Conversely, continuity forces U₁×X₂ and X₁×U₂ to be open; their intersection is U₁×U₂, so every generating rectangle is open.' },
  { section: 'topology', title: 'Proposition 2.20 — Neighbourhood test for closure', statement: 'x ∈ cl(A) iff every open neighbourhood of x intersects A.', proof: 'Prove the complement: x ∉ cl(A) iff an open neighbourhood U of x misses A. Use U = X\\cl(A) one way; the other way, X\\U is closed and contains A.' },
  { section: 'topology', title: 'Proposition 2.21 — Interior, boundary, closure', statement: 'For A⊆X: int(A)∩∂A=∅, cl(A)=int(A)∪∂A, and ∂A=cl(A)∩cl(X\\A).', proof: 'Not provided in the notes (Tutorial Question 2.6).' },
  { section: 'topology', title: 'Proposition 2.22 — Dense-set criterion', statement: 'A is dense in X iff every nonempty open subset of X intersects A.', proof: 'If an open U misses A, the closed set X\\U contains cl(A), contradicting density. Conversely, if cl(A)≠X, the nonempty open X\\cl(A) misses A.' },
  { section: 'metric-topology', title: 'Proposition 2.24 — A metric induces a topology', statement: 'The metric-open subsets form a topology, generated by the open balls.', proof: 'Combine ∅ and X being open, arbitrary unions of opens (2.9), finite intersections (2.10), and the fact every open is a union of balls.' },
  { section: 'connectedness', title: 'Proposition 2.29 — Clopen sets and boundary', statement: 'S is clopen iff ∂S is empty.', proof: 'Use cl(S)=int(S) ⊔ ∂S. If S is clopen then cl(S)=int(S)=S. Conversely ∂S=∅ gives cl(S)=int(S), forcing S to equal both.' },
  { section: 'connectedness', title: 'Proposition 2.30 — Disconnection via clopen sets', statement: 'X is disconnected iff it has a nonempty proper clopen subset.', proof: 'A separation X=U⊔V makes U clopen. Conversely, a nonempty proper clopen U gives the separation U and X\\U.' },
  { section: 'connectedness', title: 'Proposition 2.31 — Three tests for connectedness', statement: 'X is connected iff every continuous map X→D to a discrete space is constant; it suffices to test D={0,1}.', proof: 'A nonconstant map to {0,1} pulls back the two singletons to a separation. For connected X, the fibres of any map to a discrete D are open; two nonempty fibres would disconnect X.' },
  { section: 'connectedness', title: 'Proposition 2.32 — Continuous images are connected', statement: 'If f:X→Y is continuous and surjective and X is connected, then Y is connected.', proof: 'For any continuous g:Y→{0,1}, g∘f is constant. Surjectivity forces g constant; apply Proposition 2.31.' },
  { section: 'connectedness', title: 'Proposition 2.33 — ℝ is connected', statement: 'The real line with its Euclidean topology is connected.', proof: 'Assume a nonempty clopen U and choose x∈U. Use a supremum argument on points reachable from x inside U; openness of U and its complement rules out a finite boundary point. Thus U=ℝ.' },
  { section: 'connectedness', title: 'Proposition 2.34 — Connected subsets of ℝ', statement: 'The connected subsets of ℝ are exactly the nonempty intervals.', proof: 'A non-interval S has a missing point between two of its points; cutting there separates S. Conversely, a separation of an interval would yield a forbidden boundary gap, using connectedness of ℝ/order completeness.' },
  { section: 'connectedness', title: 'Corollary 2.35 — Intermediate Value Theorem', statement: 'If X is connected, f:X→ℝ continuous, and f(x)<r<f(y), then f(z)=r for some z∈X.', proof: 'By Proposition 2.32, f(X) is connected; by Proposition 2.34 it is an interval, so it contains r.' },
  { section: 'compactness', title: 'Proposition 2.36 — Relative compactness criterion', statement: 'K⊆X is compact iff every family of open subsets of X covering K has a finite subfamily covering K.', proof: 'Translate between covers open in K and ambient opens using the subspace topology: every K-open is K∩U for some X-open U.' },
  { section: 'compactness', title: 'Proposition 2.37 — Compact subsets of Hausdorff spaces', statement: 'A compact subset K of a Hausdorff space X is closed.', proof: 'For x∉K, separate x from each k∈K by Uₖ,Vₖ. Compactness reduces {Uₖ} to finitely many; intersect the matching Vₖ to get a neighbourhood of x disjoint from K.' },
  { section: 'compactness', title: 'Proposition 2.38 — Closed subset of compact is compact', statement: 'A closed subset K of a compact space X is compact.', proof: 'Add the open set X\\K to an open cover of K, producing a cover of X. Take a finite subcover, then discard X\\K.' },
  { section: 'compactness', title: 'Proposition 2.39 — Continuous image of compact is compact', statement: 'If X is compact and f:X→Y continuous, then f(X) is compact.', proof: 'Pull an open cover of f(X) back along f. Take a finite subcover of X, then push the corresponding finite family forward.' },
  { section: 'compactness', title: 'Proposition 2.40 — Closed map with compact fibres is proper', statement: 'If f:X→Y is closed and every fibre f⁻¹(y) is compact, then inverse images of compact sets are compact.', proof: 'Cover f⁻¹(K). Compactness of each fibre gives a finite local subcover; closedness creates an open neighbourhood of each y where that same finite family works. Compactness of K finishes.' },
  { section: 'compactness', title: 'Theorem 2.41 — Compact products', statement: 'If X₁ is compact, π₂:X₁×X₂→X₂ is closed and proper. Hence a product of two compact spaces is compact.', proof: 'Use the tube argument to show π₂ is closed. Its fibres are copies of compact X₁, so 2.40 makes π₂ proper. If X₂ is compact, π₂⁻¹(X₂)=X₁×X₂ is compact.' },
  { section: 'sequences', title: 'Proposition 2.42 — Limits and closed sets', statement: 'A convergent sequence is eventually in every open neighbourhood of its limit; if all terms lie in S, its limit lies in cl(S).', proof: 'Choose a ball around the limit inside the given open. Convergence gives eventual membership. Then every neighbourhood meets S, so apply 2.20.' },
  { section: 'sequences', title: 'Proposition 2.43 — Equivalent sequences share limits', statement: 'If d(xₙ,yₙ)→0, then xₙ→x iff yₙ→x.', proof: 'Choose N₁ with d(xₙ,yₙ)<ε/2 and N₂ with d(xₙ,x)<ε/2. The triangle inequality gives d(yₙ,x)<ε.' },
  { section: 'sequences', title: 'Theorem 2.44 — Sequential continuity', statement: 'For metric spaces, f is continuous at x iff xₙ→x always implies f(xₙ)→f(x).', proof: 'Forward: use the ε–δ condition. Reverse: if continuity fails, choose xₙ in B₁/ₙ(x) whose images stay outside a fixed ε-ball; then xₙ→x but f(xₙ)↛f(x).' },
  { section: 'cauchy', title: 'Proposition 2.45 — Convergent implies Cauchy', statement: 'Every convergent sequence in a metric space is Cauchy.', proof: 'For ε>0, eventually d(xₙ,x)<ε/2. Then d(xₙ,xₘ)≤d(xₙ,x)+d(x,xₘ)<ε.' },
  { section: 'cauchy', title: 'Proposition 2.47 — Complete subspaces', statement: 'If X is complete, S⊆X is complete iff S is closed.', proof: 'If S is complete, any x∈cl(S) is a limit of a sequence in S; it is Cauchy and must converge in S. If S is closed, a Cauchy sequence in S converges in X and its limit remains in S.' },
  { section: 'cauchy', title: 'Proposition 2.48 — Distances of Cauchy sequences', statement: 'If (xₙ) and (yₙ) are Cauchy, then (d(xₙ,yₙ)) is Cauchy in ℝ.', proof: 'The notes defer the inequality chase to Exercise 1.56: use |d(xₙ,yₙ)−d(xₘ,yₘ)|≤d(xₙ,xₘ)+d(yₙ,yₘ).' },
  { section: 'cauchy', title: 'Proposition 2.49 — Equivalence preserves Cauchy', statement: 'Equivalent sequences are either both Cauchy or both non-Cauchy.', proof: 'The notes defer the inequality chase to Exercise 1.57. Combine d(yₙ,yₘ)≤d(yₙ,xₙ)+d(xₙ,xₘ)+d(xₘ,yₘ) with equivalence and Cauchyness.' },
  { section: 'cauchy', title: 'Proposition 2.52 — Uniform continuity preserves Cauchy', statement: 'A uniformly continuous function maps Cauchy sequences to Cauchy sequences.', proof: 'Given ε, uniform continuity supplies δ globally. Cauchyness gives d(xₙ,xₘ)<δ eventually, hence d(f(xₙ),f(xₘ))<ε.' },
  { section: 'cauchy', title: 'Proposition 2.53 — Compact-domain continuity is uniform', statement: 'A continuous map from a compact metric space is uniformly continuous.', proof: 'For each x choose a continuity radius δ(x), and cover X by half-radius balls. Take a finite subcover and the minimum half-radius. Nearby s,t land in the same ε/2 image ball, so their images are ε-close.' },
  { section: 'completions', title: 'Proposition 2.54 — Distance in a completion', statement: 'If φ(xₙ)→x and φ(yₙ)→y in a completion, then d̄(x,y)=lim d(xₙ,yₙ).', proof: 'Pairs (φ(xₙ),φ(yₙ)) converge to (x,y) in the product sup metric. Apply continuity of the distance function and use that φ is an isometry.' },
  { section: 'completions', title: 'Theorem 2.55 — Every metric space has a completion', statement: 'Every metric space (X,d) admits a complete metric space containing an isometric dense copy of X.', proof: 'Take equivalence classes of Cauchy sequences; set d̄([xₙ],[yₙ])=lim d(xₙ,yₙ). Embed x as its constant sequence. Density comes from approximating [xₙ] by x_N. For completeness, approximate a Cauchy sequence of classes by embedded points and use the resulting diagonal Cauchy sequence.' },
  { section: 'completions', title: 'Proposition 2.56 — Extension from a dense subset', statement: 'A uniformly continuous f:D→W, with D dense in Z and W complete, extends uniquely and uniformly continuously to Z. If f is an isometry, so is the extension.', proof: 'For z choose xₙ∈D with xₙ→z and define f̄(z)=lim f(xₙ). Uniform continuity makes the image Cauchy and proves independence of the choice. Approximation proves uniform continuity; density gives uniqueness. Pass distances to limits for the isometry case.' },
  { section: 'completions', title: 'Corollary 2.57 — Extending maps; uniqueness of completion', statement: 'Uniformly continuous maps (and isometries) extend uniquely between completions. Any two completions of X are isometric.', proof: 'Apply 2.56 to the dense embedded copy of X. For two completions, extend the isometry between their dense copies; it is injective, and completeness plus density shows it is surjective.' },
];

const definitionCards = [
  { section: 'metrics', title: 'Definition — Metric', statement: 'A metric on X is a function d:X×X→[0,∞) that is positive definite, symmetric, and satisfies the triangle inequality.', cloze: 'A metric on X is a function d:X×X→___ that is ___ definite, ___, and satisfies the ___ inequality.' },
  { section: 'metrics', title: 'Definition — Metric space', statement: 'A metric space is a pair (X,d), where X is a set and d is a metric on X.', cloze: 'A metric space is a pair (___,___), where ___ is a set and ___ is a metric on it.' },
  { section: 'metrics', title: 'Definition — Isometry', statement: 'An isometry φ:(X,dX)→(Y,dY) preserves distance: dY(φ(x),φ(y))=dX(x,y) for all x,y∈X.', cloze: 'An isometry φ:(X,dX)→(Y,dY) preserves ___: dY(φ(x),φ(y))=___ for all x,y∈X.' },
  { section: 'open-sets', title: 'Definition — Open ball', statement: 'For x∈X and r>0, the open ball Bᵣ(x) is {y∈X:d(x,y)<r}.', cloze: 'For x∈X and r>0, the open ball Bᵣ(x) is {y∈X : d(x,y) ___ r}.' },
  { section: 'open-sets', title: 'Definition — Open subset', statement: 'A subset U of a metric space is open if every x∈U has some r>0 for which Bᵣ(x)⊆U.', cloze: 'A subset U of a metric space is open if every x∈___ has some r___0 for which Bᵣ(x) ___ U.' },
  { section: 'topology', title: 'Definition — Topology', statement: 'A topology T on X contains ∅ and X and is closed under arbitrary unions and finite intersections.', cloze: 'A topology T on X contains ___ and ___ and is closed under arbitrary ___ and finite ___.' },
  { section: 'topology', title: 'Definition — Continuous map', statement: 'A map f:X→Y is continuous when f⁻¹(U) is open in X for every open U⊆Y.', cloze: 'A map f:X→Y is continuous when ___ is open in X for every ___ U⊆Y.' },
  { section: 'topology', title: 'Definition — Closure and dense subset', statement: 'The closure cl(A) is the smallest closed set containing A. The set A is dense in X when cl(A)=X.', cloze: 'The closure cl(A) is the ___ closed set containing A. The set A is dense in X when cl(A)=___.' },
  { section: 'connectedness', title: 'Definition — Connected space', statement: 'A space X is connected if it cannot be written as a disjoint union of two nonempty open subsets.', cloze: 'A space X is connected if it cannot be written as a ___ union of two ___ open subsets.' },
  { section: 'compactness', title: 'Definition — Compact space', statement: 'A space is compact if every open cover has a finite subcover.', cloze: 'A space is compact if every ___ cover has a ___ subcover.' },
  { section: 'sequences', title: 'Definition — Convergent sequence', statement: 'A sequence (xₙ) converges to x when, for every ε>0, eventually d(xₙ,x)<ε.', cloze: 'A sequence (xₙ) converges to x when, for every ε>0, ___ d(xₙ,x)___ε.' },
  { section: 'cauchy', title: 'Definition — Cauchy sequence', statement: 'A sequence (xₙ) is Cauchy when, for every ε>0, eventually d(xₙ,xₘ)<ε for all sufficiently large n,m.', cloze: 'A sequence (xₙ) is Cauchy when, for every ε>0, d(xₙ,xₘ)___ε for all sufficiently large ___ and ___.' },
  { section: 'cauchy', title: 'Definition — Complete metric space', statement: 'A metric space is complete if every Cauchy sequence converges to a point of the space.', cloze: 'A metric space is complete if every ___ sequence ___ to a point of the space.' },
  { section: 'completions', title: 'Definition — Completion', statement: 'A completion of X is a complete metric space X̄ together with an isometry φ:X→X̄ whose image is dense.', cloze: 'A completion of X is a ___ metric space X̄ together with an ___ φ:X→X̄ whose image is ___.' },
];

const makeId = title => title.toLowerCase().replace(/[—–]/g, '-').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const makeCloze = statement => {
  const terms = ['arbitrary collection', 'finite', 'continuous', 'compact', 'connected', 'closed', 'Cauchy', 'uniformly', 'complete', 'dense', 'isometric'];
  let prompt = statement;
  let gaps = 0;
  terms.forEach(term => {
    if (gaps < 3 && new RegExp(term, 'i').test(prompt)) {
      prompt = prompt.replace(new RegExp(term, 'i'), '___');
      gaps += 1;
    }
  });
  if (!gaps) prompt = prompt.replace(/\b(is|are|iff|if)\b/i, '___');
  return prompt;
};

export const metricCards = [...definitionCards, ...resultCards].map(card => ({
  ...card,
  id: makeId(card.title),
  kind: card.title.startsWith('Definition') ? 'definition' : 'theorem',
  cloze: card.cloze || makeCloze(card.statement),
}));

// Each edge joins one precise definition/result to another precise result.
export const dependencies = [
  ['definition-open-subset', 'proposition-2-9-arbitrary-unions-of-opens'],
  ['definition-open-subset', 'proposition-2-10-finite-intersections-of-opens'],
  ['proposition-2-9-arbitrary-unions-of-opens', 'proposition-2-24-a-metric-induces-a-topology'],
  ['proposition-2-10-finite-intersections-of-opens', 'proposition-2-24-a-metric-induces-a-topology'],
  ['definition-topology', 'proposition-2-15-comparing-topologies'],
  ['definition-continuous-map', 'proposition-2-18-product-projections'],
  ['proposition-2-20-neighbourhood-test-for-closure', 'proposition-2-22-dense-set-criterion'],
  ['definition-connected-space', 'proposition-2-30-disconnection-via-clopen-sets'],
  ['proposition-2-30-disconnection-via-clopen-sets', 'proposition-2-31-three-tests-for-connectedness'],
  ['proposition-2-31-three-tests-for-connectedness', 'proposition-2-32-continuous-images-are-connected'],
  ['proposition-2-32-continuous-images-are-connected', 'corollary-2-35-intermediate-value-theorem'],
  ['proposition-2-34-connected-subsets-of', 'corollary-2-35-intermediate-value-theorem'],
  ['definition-compact-space', 'proposition-2-38-closed-subset-of-compact-is-compact'],
  ['proposition-2-39-continuous-image-of-compact-is-compact', 'theorem-2-41-compact-products'],
  ['proposition-2-40-closed-map-with-compact-fibres-is-proper', 'theorem-2-41-compact-products'],
  ['definition-convergent-sequence', 'proposition-2-45-convergent-implies-cauchy'],
  ['definition-cauchy-sequence', 'proposition-2-45-convergent-implies-cauchy'],
  ['definition-complete-metric-space', 'proposition-2-47-complete-subspaces'],
  ['proposition-2-45-convergent-implies-cauchy', 'proposition-2-47-complete-subspaces'],
  ['proposition-2-48-distances-of-cauchy-sequences', 'theorem-2-55-every-metric-space-has-a-completion'],
  ['definition-completion', 'theorem-2-55-every-metric-space-has-a-completion'],
  ['theorem-2-55-every-metric-space-has-a-completion', 'corollary-2-57-extending-maps-uniqueness-of-completion'],
  ['proposition-2-56-extension-from-a-dense-subset', 'corollary-2-57-extending-maps-uniqueness-of-completion'],
];
